name: Move to docs for GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Move files to docs
        run: |
          rm -rf docs
          cp -r toDo docs

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs
          git commit -m "Move to docs for GitHub Pages" || echo "No changes to commit"
          git push origin main
